### ISSUE TITLE
Problem with fakery when cloud_item is enabled

### ISSUE THREAD

**Issue by 3raven** [PiDemon/Fakery#1]
Hi,
I tried your mod, it works unless cloud_item is enabled, and when cloud item is enabled items from fakery are no longer defined.

**Comment by PiDemon** [comment]
Are you sure that you have `vehicle_mash` enabled with cloud items, as it is a dependency of cloud items?

**Comment by 3raven** [comment]
I tried again with vehicle_mash enabled, and I still have the same problem

**Comment by PiDemon** [comment]
Hmm, very strange. This doesn't seem to happen to me. Are you absolutely sure that you have `worldedit` and `vehicle_mash` enabled and are using the minetest game or something else that provides `default`?

**Comment by 3raven** [comment]
I did another test, the problem was an unsatisfied dependency of vehicule_mash to worldedit and lib_mount. It s weird to need worldedit, but with worldedit enabled it works.

**Comment by PiDemon** [comment]
Well, I'm glad you figured it out. I have no idea why unsatisfied dependencies for cloud items was causing undefined items in this mod.
